version: '3.2'
services:
  nginx:  
    image: maclarensg/nginx
    tty: true
    hostname: feproxy
    container_name: feproxy
    volumes:
      - /home/gavinyap/docker/nginx/www:/var/nginx/www
      - /home/gavinyap/docker/nginx/log:/var/nginx/log
      - /home/gavinyap/docker/nginx/config:/var/nginx/config
    ports:
      - "80:80"
      - "443:443"
    entrypoint: /usr/bin/run.sh